name: dynamedico
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <8.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  url_launcher:
  firebase_auth:
  firebase_database:
  cloud_firestore:
  firebase_core:
  shared_preferences:
  cloud_functions:
  firebase_storage: ^1.0.4
  firebase_messaging:
  barcode_scan:
  image_picker: ^0.4.12+1
  google_sign_in: ^3.2.4
  smooth_star_rating: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf
  - family: MontserratBold
    fonts:
    - asset: assets/fonts/Montserrat-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
  - assets/